# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('sets', models.PositiveSmallIntegerField(null=True)),
                ('reps', models.PositiveSmallIntegerField(null=True)),
                ('weight_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_amrap', models.NullBooleanField()),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.NullBooleanField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.Exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('weight_progression', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.Week')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'NOT_STARTED'), (1, 'IN_PROGRESS'), (2, 'FINISHED')], default=0)),
                ('finished_at', models.DateTimeField(db_index=True, editable=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.Workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.WorkoutLog'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.ExerciseType'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_tracker.Workout'),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set([('week', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together=set([('program', 'name')]),
        ),
    ]
