# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='key',
        ),
        migrations.RemoveField(
            model_name='week',
            name='key',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='key',
        ),
    ]
