# Generated by Django 2.0.4 on 2018-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_auto_20180423_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='completed',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='amrap_reps',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NOT_STARTED'), (1, 'IN_PROGRESS'), (2, 'FINISHED'), (3, 'FAILED')], default=0),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NOT_STARTED'), (1, 'IN_PROGRESS'), (2, 'FINISHED'), (3, 'FAILED')], default=0),
        ),
    ]
