# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0003_auto_20180422_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevolume',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_tracker.Workout'),
        ),
    ]
