# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0004_auto_20180422_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
