# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0005_week_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisevolume',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
